networks:
  process:
    driver: bridge
    ipam:
      config:
        - subnet: 172.23.0.0/16
          gateway: 172.23.0.1

services:
  process_app:
    build: .
    container_name: process_app
    ports:
      - "${SPRING_BOOT_PORT}:8080"
    env_file:
      - .env
    networks:
      - process
